const courses = [
    { id: 0, course: "BBA- Bachelor of Business Administration" },
    { id: 1, course: "BMS- Bachelor of Management Science" },
    { id: 2, course: "BFA- Bachelor of Fine Arts" },
    { id: 3, course: "BEM- Bachelor of Event Management" },
    { id: 4, course: "Integrated Law Course- BA + LL.B" },
    { id: 5, course: "BJMC- Bachelor of Journalism and Mass Communication" },
    { id: 6, course: "BFD- Bachelor of Fashion Designing" },
    { id: 7, course: "BSW- Bachelor of Social Work" },
    { id: 8, course: "BBS- Bachelor of Business Studies" },
    { id: 9, course: "BTTM- Bachelor of Travel and Tourism Management" },
    { id: 10, course: "B.Sc- Interior Design" },
    { id: 11, course: "B.Sc.- Hospitality and Hotel Administration" },
    { id: 12, course: "Bachelor of Design (B. Design)" },
    { id: 13, course: "Bachelor of Performing Arts" },
    { id: 14, course: "BA in History" },
    { id: 15, course: "BE/B.Tech- Bachelor of Technology" },
    { id: 16, course: "B.Arch- Bachelor of Architecture" },
    { id: 17, course: "BCA- Bachelor of Computer Applications" },
    { id: 18, course: "B.Sc.- Information Technology" },
    { id: 19, course: "B.Sc- Nursing" },
    { id: 20, course: "BPharma- Bachelor of Pharmacy" },
    { id: 21, course: "B.Sc- Interior Design" },
    { id: 22, course: "BDS- Bachelor of Dental Surgery" },
    { id: 23, course: "Animation, Graphics and Multimedia" },
    { id: 24, course: "B.Sc. - Nutrition & Dietetics" },
    { id: 25, course: "BPT- Bachelor of Physiotherapy" },
    { id: 26, course: "B.Sc- Applied Geology" },
    { id: 27, course: "BA/B.Sc. Liberal Arts" },
    { id: 28, course: "B.Sc.- Physics" },
    { id: 29, course: "B.Sc. Chemistry" },
    { id: 30, course: "B.Sc. Mathematics" },
];

export default courses;
